# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataplot', '0002_auto_20171213_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selected_Site',
            new_name='SelectedSite',
        ),
    ]
